### PR TITLE
Various fixes for ESMPy testing and documentation

### PR DESCRIPTION
**Pull request by billsacks**
This includes an updated fix to the documentation from #92 (which this supersedes) along with some fixes for ESMPy testing from @rokuingh and myself.

Once @rokuingh approves, I'll merge this to develop. Then if @theurich is okay with it, we can also get it onto the 8.4.0 release branch.

### CODE REVIEW

**Comment by rokuingh** [comment]
@billsacks I just added the updates to the data directory access for the examples and jupyter notebooks. Please run the testing one more time on your mac environment.

**Comment by billsacks** [comment]
@rokuingh I just ran testing on my Mac. I *think* it's all good, but I'm having trouble telling definitively. I am attaching the test output for you to double-check.
[esmpy8.5.0b1-petx1.test.txt](https://github.com/esmf-org/esmf/files/9834520/esmpy8.5.0b1-petx1.test.txt)
[esmpy8.5.0b1-petx4.test.txt](https://github.com/esmf-org/esmf/files/9834521/esmpy8.5.0b1-petx4.test.txt)
[esmpy8.5.0b1-petx6.test.txt](https://github.com/esmf-org/esmf/files/9834522/esmpy8.5.0b1-petx6.test.txt)

**Comment by rokuingh** [comment]
@billsacks looks good, for future reference
`tail -1 *.test`
will give you a good summary of the test pass/fail counts.

**Comment by rokuingh** [comment]
@billsacks, i think a good squash merge comment for this pr is something like the following:
`work around platform specific issues with setuptools-git-versioning, update the data directory for unit tests and examples, replace inspect with site because former returns path to source directory instead of installation when called from within source, remove old data directories`

**Review by rokuingh — APPROVED** [review]
squash merge commit message: "work around platform specific issues with setuptools-git-versioning, add unit test data to download command, update the data directory for unit tests and examples, replace inspect with site because former returns path to source directory instead of installation when called from within source, remove old data directories"

**Comment by theurich** [comment]
Reviewing the nightly testing on Cheyenne, after this was merged (both develop and release/8.4.0), I find that the ESMPy testing shows issues!

E.g. see "esmpy tests" for [Cheyenne-develop-gfortran-openmpi](https://github.com/esmf-org/esmf-test-artifacts/tree/cd5d7da7b50db9d190f6b7fdcf11fd0321c34ff2/develop/gfortran/10.1.0/O/openmpi/4.0.5/summary.dat) before the merge vs [Cheyenne-develop-gfortran-openmpi](https://github.com/esmf-org/esmf-test-artifacts/tree/73832989c22e2106844bdd7603143489d525ecd9/develop/gfortran/10.1.0/O/openmpi/4.0.5/summary.dat) after the merge.

The issue after the merge can be seen under [esmpy-test.log](https://github.com/esmf-org/esmf-test-artifacts/blob/73832989c22e2106844bdd7603143489d525ecd9/develop/gfortran/10.1.0/O/openmpi/4.0.5/out/esmpy-test.log).

**Comment by theurich** [comment]
Looking under the `esmpy` directory on Cheyenne (/glade/scratch/theurich/ESMF-Nightly-Testing/gfortran_10.1.0_openmpi_O_develop/esmf/src/addon/esmpy) I definitely see errors, in both the `esmpy8.5.0b0-petx1.test` and `PET0.ESMF_LogFile` files.

What I see is this:
```
20221022 033816.544 ERROR            PET0 ESMF_Grid.F90:29673 ESMF_GridCreateDistgridReg Input argument out of range  - - decompFlag isn't allowed to be ESMF_DECOMP_CYCLIC when creating a Grid.
20221022 033816.544 ERROR            PET0 ESMF_Grid.F90:9350 ESMF_GridCreate1PeriDimR Input argument out of range  - Internal subroutine call returned Error
20221022 033816.544 ERROR            PET0 ESMF_Grid.F90:6794 ESMF_GridCreateFrmScrip Input argument out of range  - Internal subroutine call returned Error
20221022 033816.544 ERROR            PET0 ESMF_Grid.F90:6520 ESMF_GridCreateFrmNCFile Input argument out of range  - Internal subroutine call returned Error
20221022 033816.544 ERROR            PET0 ESMF_Grid_C.F90:305 f_esmf_gridcreatefromfile Input argument out of range  - Internal subroutine call returned Error
20221022 033816.544 ERROR            PET0 ESMCI_Grid.C:658 ESMCI::Grid::createfromfile() Input argument out of range  - Internal subroutine call returned Error
20221022 033816.544 ERROR            PET0 ESMC_Grid.C:180 ESMC_GridCreateFromFile() Input argument out of range  - Internal subroutine call returned Error
```

But why would that have changed with this commit?

Also, even if a test is failing, why would it derail the whole ESMPy testing infrastructure? Maybe I am misinterpreting/misdiagnosing something, but there does certainly seem to be an issue here that we did not have before the merge of this PR.

**Pull request merged**
