### PR TITLE
Updating README

### PR DESCRIPTION
**Pull request by bekozi**
* Added some further markdown formatting. Tried to use a uniform approach to syntax highlighting and adjusted some lists.
* Changed to wrapped approach for text blocks removing a lot of newlines.
* Remove some old text.
* Improved linking.
* Changed some header names to be more concise.

See https://github.com/esmf-org/esmf/tree/60f90c68773ac7d9b7516b554526587e839ddde7 to view in markdown format.

### CODE REVIEW

**Comment by rsdunlapiv** [comment]
Some of the stuff in the README looks redundant with the user's guide.  Since there is no code in the user's guide (requiring build/testing) it might make sense to move the user's guide entirely to the GitHub wiki, or maybe to readthedocs, which allows for versioning.  Same with developers guide.  Of course, for the reference manual, we actually run the example code and the docs are intertwined with the API code, so I don't see how we could move that one out of the current process without significant effort.

**Comment by bekozi** [comment]
We could move these sections to separate markdown files in the src/doc directory and link to them. What do you think? It would make the "splash page" text a bit more concise.

**Comment by bekozi** [comment]
Got it. I think it is covered in the user's guide. Let me remove the sections and replace them with links and see how it goes.

**Comment by bekozi** [comment]
I trimmed out a bunch of text by linking to the ESMF docs: https://github.com/esmf-org/esmf/blob/31c1cd26cfeedad20003d3458cee5baf788d6a07/README.md. Hopefully I didn't go too far.

We'll need to update the other add-on READMEs at some point.

**Comment by bekozi** [comment]
I'm wondering if we should pull some text from here and put in the README: http://www.earthsystemmodeling.org/esmf_releases/public/last/ESMF_usrdoc/node2.html. We don't have any summary text.

**Comment by rsdunlapiv** [comment]
Ben, I like the shorter README.  It is simpler and points to the relevant resources.

**Pull request merged**
