### PR TITLE
Fix to propagate ESMF_Info types

### PR DESCRIPTION
**Pull request by rsdunlapiv**
This is a new PR to supersede [Dushan-NOAA](https://github.com/esmf-org/esmf/pull/51).  This ensures the type information for the Info object is correctly propagated with calling Info::get().

### CODE REVIEW

**Comment by rsdunlapiv** [comment]
This is causing a hang to ESMF_FieldIOUTest on [Hera/intel18/intelmpi](https://github.com/esmf-org/esmf-test-artifacts/blob/a660bb838d0725e3dc17e81b6bb710a8f822c537/dushan_dev_info_fix/intel/18.0.5b/O/intelmpi/2018.4.274/out/test.log#L3073).

**Comment by rsdunlapiv** [comment]
Test results now clean on Hera/intel.
https://github.com/esmf-org/esmf-test-artifacts/blob/e358c76ffeab51862fcd669b6e50c2e760c88a1c/dushan_dev_info_fix/intel/18.0.5b/g/intelmpi/2018.4.274/summary.dat#L8

**Comment by rsdunlapiv** [comment]
@theurich this is ready for merge.  After merging and new tag, I'll ask @DusanJovic-NOAA to test UFS.

**Review by theurich — APPROVED** [review]
Looks good to me. Mostly also going by the fact that the tests are clean.

**Comment by theurich** [comment]
@rsdunlapiv I will tag some time later today... just in case something else still comes in that we can capture. As always, I will run tests before tagging, so it should be stable. Then tomorrow we'll also have full set of nightlies for the tag.

**Pull request merged**
