### PR TITLE
prepare to update to pio2

### PR DESCRIPTION
**Pull request by jedwards4b**
Remove the pio subdirectory and refactor code for pio2.  This implementation does not include pio in the esmf repository, rather it treats it as an external.   I am submitting as a draft PR for discussion.

### CODE REVIEW

**Comment by jedwards4b** [comment]
It looks like the circleci code is not handling forks of the repository.

UNIT TESTS SUMMARY
Found 43 non-exhaustive multi-processor unit tests, 43 passed and 0 failed.

**Comment by rsdunlapiv** [comment]
@jedwards4b I am going to add you to esmf-org:esmf.  Can you please push your branch there and open a new PR?  Most of the "real" ESMF testing is on HPC platforms and this will allow us to test your branch more easily.

**Comment by jedwards4b** [comment]
It seems like just pushing the branch to origin was enough and I don't need to close the PR and reopen it.

**Comment by jedwards4b** [comment]
@rsdunlapiv I get the sense that the build-esmpy-docs test is broken.

**Comment by theurich** [comment]
@jedwards4b this PR draft is actually still pointing to your fork. It will be clearer to close this and open a new PR.

In order to look into your changes, what PIO2 version do I need to get and build?

**Comment by jedwards4b** [comment]
Hi Gerhard [pio2.5.4](https://github.com/NCAR/ParallelIO/releases/tag/pio2_5_4)  
After building set environment variables PIO_LIB_DIR and PIO_INCDIR

**Comment by jedwards4b** [comment]
superceeded by #32

**Pull request closed without merging**
