### PR TITLE
More doc fixes

### PR DESCRIPTION
**Pull request by theurich**
One more doc fix: Add item added section for new optional arguments added.

### CODE REVIEW

**Comment by theurich** [comment]
@oehmke - Hi Bob, please review and approve at your convenience. Thanks!

**Review by oehmke — APPROVED** [review]
Looks good. Thanks for adding that! (That interface has been around a lot longer than I thought if it has a status block...)

**Comment by theurich** [comment]
I was surprised about the status block, too. Let me check if that came in by accident at some later date. I will let you know, and if so, I will remove it.... just so much easier :-)

**Comment by theurich** [comment]
Yep, it's been there that long... I will merge the PR into release/8.5.0. FYU, online doc of the PR branch is at https://earthsystemmodeling.org/docs/nightly/fix/api-issues/ESMF_refdoc/node5.html#SECTION050366800000000000000

**Comment by oehmke** [comment]
I was just looking through the release notes, it looks like the XGrid stuff (including ESMF_FieldRegridStore() using an XGrid) came in in ESMF 5.1.0. That’s before we did the backward compatibility change, so maybe we did add it. I thought that we didn’t do it for XGrid in general, but maybe we decided to do it for this interface because it’s Field?? I always forget that XGrid has been around a long time, because it hasn’t been used much.

**Comment by oehmke** [comment]
Sounds good. Thanks!

**Pull request merged**
