### PR TITLE
Get ESMF Compiling on Cygwin, and set up a CI run

### LINKED ISSUE #136: Build config fixes for Cygwin
At Deltares we use a very old version of ESMF on Windows and I'm trying to build a recent version.

Using the MinGW build config works, but that is i686-based.

Copying some MinGW flags to the Cygwin build config gets me further, but there are some non-functional (ESMF_OS_MinGW) code-switches that still make it fail.

I would like to request permission to create a feature-branch for correcting the Cygwin flags and making the code-switches functional.

### PR DESCRIPTION
**Pull request by DWesl**
I updated my ESMF build on Cygwin, and tried to generalize my changes from the last time I did this so ESMF would still compile on Linux.

I also added a CI run to ensure ESMF compilation gets checked.  I think I set up the tests to run as well, but I'm less sure of that.

Might close #136; I'm not sure if they're after a Cygwin build of ESMF or a 64-bit MinGW/Windows build of ESMF.  PR #149 suggests they're after a MinGW-w64 build but are trying to do it in Cygwin without cross-compilers for whatever reason.

### CODE REVIEW

**Comment by theurich** [comment]
I am going to merge this PR into a branch under the esmf-org/esmf repo so we can collaborate on it better. It should be open for everyone.
@DWesl please re-open the PR from the new branch: https://github.com/esmf-org/esmf/tree/feature/esmf-cygwin-compile. Just copy your initial description. Thanks!

**Comment by DWesl** [comment]
It doesn't want to let me because I'm not a collaborator.

**Comment by theurich** [comment]
Good point... I thought we had this open, guess not. Let me discuss this with the team... we might invite you as collaborator for this.... I think it will make this easier, especially for testing the action.

**Comment by DWesl** [comment]
#202

**Pull request merged**
