### PR TITLE
Updated ESMPy README to markdown

### PR DESCRIPTION
**Pull request by bekozi**
See https://github.com/esmf-org/esmf/tree/bekozi-esmpy-readme/src/addon/ESMPy

### CODE REVIEW

**Comment by rokuingh** [comment]
@oehmke is second-order regridding supported in 3D? The ESMPy documentation says that 3D conservative regridding is fully supported, and I want to verify whether that sentence may be left over from the time before 2nd order.

**Comment by oehmke** [comment]
2nd order conservative does not support 3D. - Bob

**Comment by bekozi** [comment]
@rokuingh It sounds like you need to do updates. Are you planning to push the fixes?

**Comment by rokuingh** [comment]
ESMPy README has been updated.

**Comment by bekozi** [comment]
@rokuingh I'm trying to figure out where these conflicts came from. When you updated the esmpy readme, did you update this branch or master? If it was master, we need to move the changes over to this branch. I get one big conflict with the esmpy readme when attempting to resolve conflicts.

**Comment by bekozi** [comment]
This is full of conflicts and other things now so closing without a merge. I will commit the README changes directly.

**Pull request closed without merging**
