### PR TITLE
Jedwards/update pio to 262

### PR DESCRIPTION
**Pull request by jedwards4b**
Update ParallelIO to version 2.6.2 
It looks like this commit includes a lot of (unintentional) whitespace cleanup.

### CODE REVIEW

**Comment by theurich** [comment]
@jedwards4b fyi, I will take a look at this (and run tests) some time next week. Have a great long weekend!

**Comment by billsacks** [comment]
Although I haven't done a thorough review of what's coming in with these changes, I did check this by comparing (1) The diffs between the current ESMF ParallelIO and the official ParallelIO 2.5.10, vs. (2) The diffs between the ESMF ParallelIO and the official ParallelIO 2.6.2. To me this is the important comparison for accepting this change. What I found was that the ParallelIO in this branch is identical to the official ParallelIO 2.6.2, whereas there was a small difference betwen the ESMF ParallelIO on develop vs ParallelIO 2.5.10:

```diff
diff -r ./src/gptl/perf_utils.F90 /Users/sacks/esmf/esmf1/src/Infrastructure/IO/PIO/ParallelIO/src/gptl/perf_utils.F90
320c320
< !BOP ===========================================================================
---
> !BOPI ===========================================================================
336c336
< !EOP
---
> !EOPI
370c370
< !BOP ===========================================================================
---
> !BOPI ===========================================================================
390c390
< !EOP
---
> !EOPI
```

@theurich it looks like you changed these BOPs/EOPs to BOPI/EOPI in 07e66a46a97cca911781d64d20c04e7a2fd84a18. Is it important to carry this change forward? If so, I can add this change to this branch. Or is there a way that we can exclude this file from our documentation generation so that we don't need to keep this divergence between our ParallelIO and the official one?

I'm going to kick off testing on this branch now.

**Comment by theurich** [comment]
@billsacks 
I do remember making this change due to some issue with the docs otherwise. Quickest to just preserve the change for now.

Honestly I wonder if ParallelIIO really makes use of ProTex for documentation - or if these lines shouldn't really be removed from the official ParallelIO version. There are only two files in ParallelIO that have any ProTex instrumentation, and only the one you found causing issues. The two files are:
```
./examples/basic/kinds_mod.F90
./src/gptl/perf_utils.F90
```

**Comment by jedwards4b** [comment]
Thanks - I have submitted https://github.com/NCAR/ParallelIO/pull/1975
to remove them in the next ParallelIO tag.

**Comment by billsacks** [comment]
Thanks @jedwards4b ! I'll make the changes needed for this PR.

**Comment by billsacks** [comment]
Tests passed on my mac (gfortranclang) and cheyenne (intel). I have made the BOP -> BOPI change. I'll push a branch to the ESMF repo and enable nightly testing.

**Comment by billsacks** [comment]
Thanks, @theurich ! I was about to check on these test results and your message saved me what I'm sure would have been a puzzling experience. I have updated the version of this branch in the esmf repo to the latest develop so will see how testing looks tomorrow.

**Comment by billsacks** [comment]
@theurich I checked the nightly test results for this branch. My sense is this is probably okay, but wanted to run by you what I'm seeing:
- One less utest failure on derecho-cce-mpi-O on this branch compared with develop (haven't investigated)
- Four fewer nuopc failures on derecho-intelOneApi-mpi-O on this branch compared with the most recent testing on develop (haven't investigated)
- A couple of gaeaC5 combos haven't reported
- There were 10 nuopc failures in gaeaC5-intelOneApi-mpi-g that didn't show up on the latest develop, though did show up in the recent past on develop. From spot-checking one (SingleModelProto), the problem wasn't obvious to me
- A bunch of combos didn't report on hera

Please let me know if this seems okay to bring to develop.

I am going to change the nightly testing back to testing develop instead of this branch.

**Review by billsacks — APPROVED** [review]

**Comment by billsacks** [comment]
At @theurich 's suggestion, I went through the list of changes in PIO since 2.5.10 (from the PIO GitHub releases). Here is my annotated list. @jedwards4b I would welcome any input / corrections, especially related to which of these changes might have an impact on the use of PIO within ESMF and which would require changes to ESMF in order to take advantage of the PIO changes:

- PIO 2.6.0
    - This release supports the netcdf integration layer using Dispatch version 5. We recommend netcdf-c v4.9.2 or newer to take advantage of this feature.
        - My note: is this for using the NetCDF interface to access non-NetCDF files? I imagine changes would be needed within ESMF to take advantage of this features.
    - We have also added API's for netcdf4/hdf5 filters. These provide a full set of lossless and lossy compression techniques.
        - My note: I think we would need to extend the ESMF I/O interface to allow access to these features
- PIO 2.6.1
    - Addresses performance issues with lustre filesystems.
        - My note: My understanding is that, for CESM, changes were needed in the use of PIO to take advantage of this fix – specifically, controlling the order in which variables are written to file (grouping together variables with the same dimensions). Similar changes might be needed in ESMF if performance issues are found with I/O on lustre systems. I'm not sure if this change in PIO will have any effect without corresponding changes in ESMF.
    - Fixes issues when building with netcdf serial.
        - My note: I can't find details on this, so I'm not sure what exactly it refers to.
    - Add rpath variables to cmake build.
        - My note: just an issue when using a shared library build of ParallelIO. I'm guessing this isn't a problem for the PIO built internally as part of the ESMF build.
- PIO 2.6.2
    - Fixes scalar write issue: Scalars were being lost when the model memory usage was close to the limit for the system.
        - My note: I guess this could potentially impact writes from ESMF
    - Fixes a serial build issue.
        - My note: I'm not sure whether this would impact the internal PIO build within ESMF

My tentative suggestion for the ESMF release notes would be to keep this vague, unless we get more specific input from @jedwards4b ... something like: "Compared with the previous version of PIO (2.5.10), this version of PIO fixes a number of issues and enables some new features that we can later take advantage of in ESMF, notably for writing compressed files."

**Comment by theurich** [comment]
Thank you @billsacks for digging through the list of PIO changes and summarizing the hightlights here. I agree with your sense of keeping mention in the ESMF release notes very high level, even just mentioning that the internal version of PIO was updated to `2.6.2`, and link to the respective ParallelIO release on GitHub, for those that want to see the details.
Based on the nightly testing of the branch (the other day), and your review here, I think this is ready to be merged into `develop`. I'll approve. Please merge at your convenience. Thanks!

**Review by theurich — APPROVED** [review]
Approval based on nightly testing of the branch, and @billsacks summary.

**Pull request merged**
