### PR TITLE
Add artifacts to Spack build action for debugging

### PR DESCRIPTION
**Pull request by uturuncoglu**
This PR aims to add new feature to Spack build action to store run directory of NUOPC App Prototypes as artifacts. @theurich this is replacement of https://github.com/esmf-org/esmf/pull/194. GitHub did not allow me to create PR with the previous branch. So, I created new one.

### CODE REVIEW

**Review by theurich — APPROVED** [review]
Looks good to go. Please merge into `develop` at your convenience.

**Comment by uturuncoglu** [comment]
@theurich I started a test run https://github.com/esmf-org/esmf/actions/runs/7024221309 before merging this. Just for extra check. I think we did not know the issue yet related with the failures. Right?

**Comment by theurich** [comment]
Sounds good. And you are right, we do not know the issue yet related to the failure. Once this PR is on develop, I plan to create a new fix-branch to look into the issue, leveraging the fact that we get the artifacts now.

**Comment by theurich** [comment]
@uturuncoglu - the action has finished... looks good to go into `develop` now.

**Pull request merged**
