### PR TITLE
Fix Resource File line limit

### PR DESCRIPTION
**Pull request by danrosen25**
TYPE: documentation fix

KEYWORDS: documentation, ESMF_ConfigGetLen, Resource File

SOURCE: Daniel Rosen, NCAR

DESCRIPTION OF CHANGES: Updates Resource File line limit in ESMF Reference Manual [46.1.2 Resource files](https://earthsystemmodeling.org/docs/release/latest/ESMF_refdoc/node6.html#SECTION06091200000000000000)
* see LSZ parameter in ESMF_Config.F90
* remove commented out LSZ code

ISSUES:
https://github.com/esmf-org/esmf-support/issues/155

### CODE REVIEW

**Review by theurich — APPROVED** [review]
Looks good to be merged into develop.

**Comment by danrosen25** [comment]
Hi @theurich 
I was thinking that we also add a check for line limitations during ConfigFileLoad. If a line is greater than max(1024,ESMF_MAXPATHLEN) then ConfigFileLoad should fail.  What do you think?

**Comment by theurich** [comment]
@danrosen25 - I agree that would be good to have. Although, the implementation might be tricky. I figure that the truncation is done by the Fortran read... so to detect that a line was actually longer, you'd have to read into a longer buffer first?

**Comment by theurich** [comment]
@danrosen25, I just came across this doc change PR again. Were you expecting me to merge this? If so, I probably dropped the ball.

**Comment by danrosen25** [comment]
@theurich 
I'm comfortable with you merging it. I think the better fix needs to be implemented when there is more time.

**Review by theurich — APPROVED** [review]

**Pull request merged**
