### PR TITLE
Mods to documentation build for users

### PR DESCRIPTION
**Pull request by bekozi**

### CODE REVIEW

**Comment by theurich** [comment]
Hi Ben, why is it saying 0/2 checks OK for this PR?
-Gerhard

**Comment by bekozi** [comment]
@theurich I'm working on that now. These are the build checks for Travis-CI. I'll get them passing before the merge.

**Comment by theurich** [comment]
Now the text reads: "... will need to clone the esmf ESMF code 
repository...". I don't like the repeating esmf/ESMF part. Also, I 
prefer download instead of clone, because it is more inclusive (e.g. you 
might also use a tarball).  My suggestion is "... will need to download 
ESMF from the code repository...". The technical details and options 
should be discussed under the "download" section that is linked.

-Gerhard

**Comment by theurich** [comment]
Now the text reads: "... will need to clone the esmf ESMF code 
repository...". I don't like the repeating esmf/ESMF part. Also, I 
prefer download instead of clone, because it is more inclusive (e.g. you 
might also use a tarball).  My suggestion is "... will need to download 
ESMF from the code repository...". The technical details and options 
should be discussed under the "download" section that is linked.

**Comment by bekozi** [comment]
Makes sense. I adjusted the wording. My latex is shoddy so missed the extra "esmf"!

**Comment by theurich** [comment]
Looks good now. Thanks. Please go ahead and merge to master.

**Comment by tsinlu** [comment]
Hello, Prof. I met a question these days while I install ESMF_7_0_1r, and the details was below.
First, upziped the source code and copyed it. 
`
cd /data01/LiqlWorkSpace/Tools/ESMF
tar -vxzf esmf-ESMF_7_1_0r.tar.gz
cp -r esmf-ESMF_7_1_0r /data01/LiqlWorkSpace/tools/ESMF/esmf
`
Then, declare environment variables.

`
vim ~/.bashrc
export ESMF_DIR=/data01/LiqlWorkSpace/tools/ESMF/esmf
export instl_path=/data01/LiqlWorkSpace/tools/ESMF
export ESMF_BOPT=g
export ESMF_COMM=mpiuni
export ESMF_COMPILER=gfortran
export ESMF_ABI=64
export ESMF_INSTALL_PREFIX=$instl_path/esmf_install
# export ESMF_NETCDF=/usr/local/netcdf4
export ESMF_NETCDF_INCLUDE=$ESMF_DIR/netcdf/include
export ESMF_NETCDF_LIBPATH=$ESMF_DIR/netcdf/lib
export ESMF_NETCDF_LIBS="-lnetcdf -lnetcdff"

export ESMF_OS=Linux
export ESMF_TESTMPMD=ON
export ESMF_PTHREADS=ON
export ESMF_OPENMP=ON
export ESMF_TESTEXHAUSTIVE=ON
export ESMF_TESTHARNESS_ARRAY=RUN_ESMF_TestHarnessArrayUNI_2
export ESMF_TESTHARNESS_FIELD=RUN_ESMF_TestHarnessFieldUNI_1
export ESMF_NO_INTEGER_1_BYTE=FALSE
export ESMF_NO_INTEGER_2_BYTE=FALSE
export ESMF_FORTRANSYMBOLS=default
export ESMF_DEFER_LIB_BUILD=ON
export ESMF_TESTWITHTHREADS=OFF
export ESMF_CXXCOMPILER=g++
export ESMF_CXXLINKER=g++
export ESMF_F90COMPILER=gfortran
export ESMF_F90LINKER=gfortran
export ESMF_INSTALL_BINDIR=bin/bing/Linux.gfortran.64.mpiuni.default
export ESMF_INSTALL_MODDIR=mod/modg/Linux.gfortran.64.mpiuni.default
export ESMF_INSTALL_LIBDIR=lib/libg/Linux.gfortran.64.mpiuni.default
export ESMF_INSTALL_HEADERDIR=include
export ESMF_INSTALL_DOCDIR=doc


export ESMFBIN_PATH=$ESMF/bin/bing/Linux.gfortran.64.mpiuni.default
export ESMFLIB_PATH=$ESMF/lib/libg/Linux.gfortran.64.mpiuni.default

export MPIEXEC=$MPICH/bin/mpiexec

export MY_ESMF_REGRID=$instl_path/esmf/bin/bing/Linux.gfortran.64.mpiuni.default/ESMF_RegridWeightGen

source ~/.bashrc`
But when I compile I get an error, and I try to google to the related error further solution while there was no answer got:
image
What should I do when I met this question, looking forward to your reply.

**Comment by tsinlu** [comment]
Hello, Prof. I met a question these days while I install ESMF_7_0_1r, and the details was below.
First, upziped the source code and copyed it. 
` cd /data01/LiqlWorkSpace/Tools/ESMF \b tar -vxzf esmf-ESMF_7_1_0r.tar.gz \b cp -r esmf-ESMF_7_1_0r /data01/LiqlWorkSpace/tools/ESMF/esmf
`
Then, declare environment variables.

`
vim ~/.bashrc
export ESMF_DIR=/data01/LiqlWorkSpace/tools/ESMF/esmf
export instl_path=/data01/LiqlWorkSpace/tools/ESMF
export ESMF_BOPT=g
export ESMF_COMM=mpiuni
export ESMF_COMPILER=gfortran
export ESMF_ABI=64
export ESMF_INSTALL_PREFIX=$instl_path/esmf_install
# export ESMF_NETCDF=/usr/local/netcdf4
export ESMF_NETCDF_INCLUDE=$ESMF_DIR/netcdf/include
export ESMF_NETCDF_LIBPATH=$ESMF_DIR/netcdf/lib
export ESMF_NETCDF_LIBS="-lnetcdf -lnetcdff"

export ESMF_OS=Linux
export ESMF_TESTMPMD=ON
export ESMF_PTHREADS=ON
export ESMF_OPENMP=ON
export ESMF_TESTEXHAUSTIVE=ON
export ESMF_TESTHARNESS_ARRAY=RUN_ESMF_TestHarnessArrayUNI_2
export ESMF_TESTHARNESS_FIELD=RUN_ESMF_TestHarnessFieldUNI_1
export ESMF_NO_INTEGER_1_BYTE=FALSE
export ESMF_NO_INTEGER_2_BYTE=FALSE
export ESMF_FORTRANSYMBOLS=default
export ESMF_DEFER_LIB_BUILD=ON
export ESMF_TESTWITHTHREADS=OFF
export ESMF_CXXCOMPILER=g++
export ESMF_CXXLINKER=g++
export ESMF_F90COMPILER=gfortran
export ESMF_F90LINKER=gfortran
export ESMF_INSTALL_BINDIR=bin/bing/Linux.gfortran.64.mpiuni.default
export ESMF_INSTALL_MODDIR=mod/modg/Linux.gfortran.64.mpiuni.default
export ESMF_INSTALL_LIBDIR=lib/libg/Linux.gfortran.64.mpiuni.default
export ESMF_INSTALL_HEADERDIR=include
export ESMF_INSTALL_DOCDIR=doc


export ESMFBIN_PATH=$ESMF/bin/bing/Linux.gfortran.64.mpiuni.default
export ESMFLIB_PATH=$ESMF/lib/libg/Linux.gfortran.64.mpiuni.default

export MPIEXEC=$MPICH/bin/mpiexec

export MY_ESMF_REGRID=$instl_path/esmf/bin/bing/Linux.gfortran.64.mpiuni.default/ESMF_RegridWeightGen

source ~/.bashrc`
But when I compile I get an error, and I try to google to the related error further solution while there was no answer got:
image
What should I do when I met this question, looking forward to your reply.

**Comment by tsinlu** [comment]
Hello, Prof. I met a question these days while I install ESMF_7_0_1r, and the details was below.
First, upziped the source code and copyed it. 
`
cd /data01/LiqlWorkSpace/Tools/ESMF
tar -vxzf esmf-ESMF_7_1_0r.tar.gz
cp -r esmf-ESMF_7_1_0r /data01/LiqlWorkSpace/tools/ESMF/esmf
`
Then, declare environment variables.

`
vim ~/.bashrc
export ESMF_DIR=/data01/LiqlWorkSpace/tools/ESMF/esmf
export instl_path=/data01/LiqlWorkSpace/tools/ESMF
export ESMF_BOPT=g
export ESMF_COMM=mpiuni
export ESMF_COMPILER=gfortran
export ESMF_ABI=64
export ESMF_INSTALL_PREFIX=$instl_path/esmf_install
# export ESMF_NETCDF=/usr/local/netcdf4
export ESMF_NETCDF_INCLUDE=$ESMF_DIR/netcdf/include
export ESMF_NETCDF_LIBPATH=$ESMF_DIR/netcdf/lib
export ESMF_NETCDF_LIBS="-lnetcdf -lnetcdff"

export ESMF_OS=Linux
export ESMF_TESTMPMD=ON
export ESMF_PTHREADS=ON
export ESMF_OPENMP=ON
export ESMF_TESTEXHAUSTIVE=ON
export ESMF_TESTHARNESS_ARRAY=RUN_ESMF_TestHarnessArrayUNI_2
export ESMF_TESTHARNESS_FIELD=RUN_ESMF_TestHarnessFieldUNI_1
export ESMF_NO_INTEGER_1_BYTE=FALSE
export ESMF_NO_INTEGER_2_BYTE=FALSE
export ESMF_FORTRANSYMBOLS=default
export ESMF_DEFER_LIB_BUILD=ON
export ESMF_TESTWITHTHREADS=OFF
export ESMF_CXXCOMPILER=g++
export ESMF_CXXLINKER=g++
export ESMF_F90COMPILER=gfortran
export ESMF_F90LINKER=gfortran
export ESMF_INSTALL_BINDIR=bin/bing/Linux.gfortran.64.mpiuni.default
export ESMF_INSTALL_MODDIR=mod/modg/Linux.gfortran.64.mpiuni.default
export ESMF_INSTALL_LIBDIR=lib/libg/Linux.gfortran.64.mpiuni.default
export ESMF_INSTALL_HEADERDIR=include
export ESMF_INSTALL_DOCDIR=doc


export ESMFBIN_PATH=$ESMF/bin/bing/Linux.gfortran.64.mpiuni.default
export ESMFLIB_PATH=$ESMF/lib/libg/Linux.gfortran.64.mpiuni.default

export MPIEXEC=$MPICH/bin/mpiexec

export MY_ESMF_REGRID=$instl_path/esmf/bin/bing/Linux.gfortran.64.mpiuni.default/ESMF_RegridWeightGen

source ~/.bashrc
`
But when I compile I get an error, and I try to google to the related error further solution while there was no answer got:
image
What should I do when I met this question, looking forward to your reply.

**Comment by tsinlu** [comment]
<font fc="Times New Roman" size=14>Hello, engineers.</font>
<font fc="Times New Roman" size=14>In the past two days, when I installed esmf_7_0_1r, I encountered an error, and I tried many times and still did not solve it. See below for a more detailed description</font>
<font fc="Times New Roman" size=14>First I downloaded the binary source code, unzipped it and copied it to the installation path.</font>
```shell
cd /data01/LiqlWorkSpace/Tools/ESMF
cp -r esmf-ESMF_7_1_0r /data01/LiqlWorkSpace/Tools/ESMF/esmf
```
<font fc="Times New Roman" size=14>Then write the environment variables to the bashrc file. </font>
```shell
vim ~/.bashrc
#---------------ESMF environment variables begin-----------
export ESMF_DIR=/data01/LiqlWorkSpace/tools/ESMF/esmf
export instl_path=/data01/LiqlWorkSpace/tools/ESMF
export ESMF_BOPT=g
export ESMF_COMM=mpiuni
export ESMF_COMPILER=gfortran
export ESMF_ABI=64
export ESMF_INSTALL_PREFIX=$instl_path/esmf_install

# export ESMF_NETCDF=/usr/local/netcdf4
export ESMF_NETCDF_INCLUDE=$ESMF_DIR/netcdf/include
export ESMF_NETCDF_LIBPATH=$ESMF_DIR/netcdf/lib
export ESMF_NETCDF_LIBS="-lnetcdf -lnetcdff"

export ESMF_OS=Linux
export ESMF_TESTMPMD=ON
export ESMF_PTHREADS=ON
export ESMF_OPENMP=ON
export ESMF_TESTEXHAUSTIVE=ON
export ESMF_TESTHARNESS_ARRAY=RUN_ESMF_TestHarnessArrayUNI_2
export ESMF_TESTHARNESS_FIELD=RUN_ESMF_TestHarnessFieldUNI_1
export ESMF_NO_INTEGER_1_BYTE=FALSE
export ESMF_NO_INTEGER_2_BYTE=FALSE
export ESMF_FORTRANSYMBOLS=default
export ESMF_DEFER_LIB_BUILD=ON
export ESMF_TESTWITHTHREADS=OFF
export ESMF_CXXCOMPILER=g++
export ESMF_CXXLINKER=g++
export ESMF_F90COMPILER=gfortran
export ESMF_F90LINKER=gfortran
export ESMF_INSTALL_BINDIR=bin/bing/Linux.gfortran.64.mpiuni.default
export ESMF_INSTALL_MODDIR=mod/modg/Linux.gfortran.64.mpiuni.default
export ESMF_INSTALL_LIBDIR=lib/libg/Linux.gfortran.64.mpiuni.default
export ESMF_INSTALL_HEADERDIR=include
export ESMF_INSTALL_DOCDIR=doc


export ESMFBIN_PATH=$ESMF/bin/bing/Linux.gfortran.64.mpiuni.default
export ESMFLIB_PATH=$ESMF/lib/libg/Linux.gfortran.64.mpiuni.default

export MPIEXEC=$MPICH/bin/mpiexec

export MY_ESMF_REGRID=$instl_path/esmf/bin/bing/Linux.gfortran.64.mpiuni.default/ESMF_RegridWeightGen
```
<font fc="Times New Roman" size=14>Then resource bashrc file, and make it.</font>
```shell
resource ~/.bashrc
make check -j
```
<font fc="Times New Roman" size=14>Then there will be an error, the error message is as shown in the figure.</font>
image
<font fc="Times New Roman" size=14>I tried searching for this question but didn't find the relevant entry, after checking the declared variables and trying to reinstall, replace the installation package, reinstall LAPACK, etc., it's still the same error, which makes me confused , I don't know where I went wrong in the installation, hope you can help me with this.</font>

**Pull request merged**
