### PR TITLE
Allow to query allocation status of LocalArray, Array and Field

### PR DESCRIPTION
**Pull request by uturuncoglu**
This PR aims to provide interface to allow users to query allocation status (user vs. ESMF allocated) for ESMF_LocalArrayGet(), ESMF_ArrayGet() and ESMF_FieldGet() calls. It also updates unit tests to test new functionality.

### CODE REVIEW

**Comment by uturuncoglu** [comment]
@theurich I know you are busy but please let me know how this PR looks when you have time. I think it is not urgent and can be done after release.

**Comment by theurich** [comment]
Sorry for the delay @uturuncoglu. This will be after the release.

**Comment by uturuncoglu** [comment]
@theurich Okay. That sounds fine. I just want to remind you. Thanks.

**Comment by theurich** [comment]
@ufuk -  I reviewed the changes on your branch. There were some issues, and I started a new branch, same name, but under the official ESMF repo: https://github.com/esmf-org/esmf/tree/feature/is_allocated. If you agree, I think it is best to close this PR, and open a new one based on the new branch.

**Comment by theurich** [comment]
Sorry, wrong @ufuk... meant @uturuncoglu.

**Comment by uturuncoglu** [comment]
A new PR based on this is created: https://github.com/esmf-org/esmf/pull/56

**Pull request closed without merging**
