### PR TITLE
catch a different pio error message

### PR DESCRIPTION
**Pull request by jedwards4b**
In some cases an attempt to open a netcdf-4 file with pnetcdf will generate a PIO_ENOTBUILT error instead of PIO_EINVAL.   This will capture that error and attempt to reopen with netcdf.

### CODE REVIEW

**Comment by theurich** [comment]
@jim, is this already part of a more recent PIO release tag? If so, should we just update PIO under ESMF develop?

**Comment by jedwards4b** [comment]
@theurich the change here is in esmf, not in pio.

**Comment by theurich** [comment]
@jim - sorry, I should have looked at the file that changed before making that comment. 
On the PIO topic though, is there a new PIO release tag (with the recent changes) that we should update to under ESMF?

**Comment by theurich** [comment]
@oehmke - please review Jim's PR since it is in Mesh code. Thanks.

**Comment by jedwards4b** [comment]
@theurich no, esmf is on the current pio release.

**Review by oehmke — COMMENTED** [review]
Line 424 and 428 look like they are dumping error information to stdout. We usually just write error info to the log files. I was wondering if these are left over debug statements. If not, can we take them out and let the PIO error handing on line 430 write the error to the log files instead?

**Comment by jedwards4b** [comment]
@oehmke Sorry, I've removed the debug statements.

**Review by oehmke — COMMENTED** [review]
Thanks Jim!   Sorry, I just noticed one more thing. I think that you need to compare each variable with a ==. I.e.  (piorc == PIO_EINVAL) || (piorc == PIO_ENOTBUILT)  I think that what you have now does an or of the truth value of (piorc==PIO_EINVAL) with just PIO_ENOTBUILT.

**Comment by jedwards4b** [comment]
@oehmke no worries - good catch.   I am retesting with the change now and will push shortly.

**Review by oehmke — APPROVED** [review]
Thanks! Looks good to me now.

**Comment by theurich** [comment]
@jedwards4b and @oehmke - I think this PR got lost in the shuffle. It's merged into develop now and will make it into the next 8.5.0 beta tag.

**Pull request merged**
