### PR TITLE
Esmpy doc circleci

### PR DESCRIPTION
**Pull request by him-28**
Dev guide and esmpy check

### CODE REVIEW

**Comment by bekozi** [comment]
After looking at this, I think it makes sense to branch from develop for these changes. Nothing related to esmpy for the dev guide push and that work should be kept separate. Do you want to just patch your changes against develop and do a new PR?

The esmpy changes are not ready to be merged yet.

**Comment by bekozi** [comment]
Actually, if you are okay with this hanging out there for a few more days, I'll just push to this and get the esmpy docs building as part of the PR. No need to complicate things further.

**Comment by him-28** [comment]
> Actually, if you are okay with this hanging out there for a few more days, I'll just push to this and get the esmpy docs building as part of the PR. No need to complicate things further.

Sure, that works , also push the dev_guide changes to PR .

**Comment by bekozi** [comment]
> Sure, that works , also push the dev_guide changes to PR .

These are already included in this PR, correct? I am planning to just push to the branch so my new commits will be included in this PR. I just want to make sure I'm not missing any additional dev_guide requirements.

**Comment by bekozi** [comment]
I noticed we don't a github.io set-up for this yet, so nothing to do but confirm the push worked. I'll get this merged so we can check the dev guide.

**Comment by bekozi** [comment]
@him-28/@rsdunlapiv, dev guild should be auto-pushing now: https://app.circleci.com/pipelines/github/esmf-org/esmf/343/workflows/e72ca7cc-e359-401a-a23e-e045bdd85db2/jobs/567

**Pull request merged**
