### PR TITLE
Modify ESMX build utilities

### PR DESCRIPTION
**Pull request by danrosen25**
These changes enhance the user experience when using ESMX by integrating the component build step into the ESMX build. In the best case scenario the component projects builds and installs libraries using cmake and exports a CMake configuration file including the NUOPC cap. Several other options are available for searching for libraries and fortran modules. Note that external libraries without a CMake configuration file can be particularly challenging and make use of the link\_libraries and link\_paths options. link\_paths accepts both a full path or an environment variable.

### Build Types
**Auto**<br>
The ESMX build system searches for CMakeLists.txt, Makefile, and a build\_script in order in the source\_dir and uses the first build option it finds. If no build files are found then the ESMX build system searches for the CMake configuration file, fortran module, and libraries in the install\_prefix directory but does not build the model. If no build option, CMake configuration, or libraries are found then the build fails.

**CMake**<br>
The ESMX build system searches for CMakeLists.txt in the source\_dir and builds using CMake. Once built, the ESMX build system searches for the CMake configuration file and libraries in the install\_prefix directory.

**Make**<br>
The ESMX build system searches for Makefile in the source\_dir and builds using Make. Once built, the ESMX build system searches for libraries and fortran modules in the install\_prefix directory.

**Script**<br>
The ESMX build system searches for a build\_script in the source\_dir and builds using this script. Once built, the ESMX build system searches for libraries and fortran modules in the install\_prefix directory.

**None**<br>
The ESMX build system will not build the component. The ESMX build system searches for the CMake configuration file, fortran module, and libraries in the install\_prefix directory.

See documentation here [https://github.com/esmf-org/esmf/tree/feature/esmx_cmake/src/addon/ESMX](https://github.com/esmf-org/esmf/tree/feature/esmx_cmake/src/addon/ESMX)

see examples here: [https://github.com/esmf-org/nuopc-app-prototypes/tree/feature/esmx_cmake](https://github.com/esmf-org/nuopc-app-prototypes/tree/feature/esmx_cmake)

Changes
* adds ESMX_Builder script
* add ESMX_BUILD_FILE argument (default esmxBuild.yaml)
* removes configuration option requirements
* add build configuration options (see table below)

| Option          | Description                                       | Default                |
| --------------- | ------------------------------------------------- | ---------------------- |
| build\_type     | auto, cmake, make, script, none                   | auto                   |
| build\_script   | build script                                      | compile                |
| build\_args     | build arguments passed to ExternalProject         | *None*                 |
| source\_dir     | source directory for build                        | *component-name*       |
| cmake\_config   | CMake configuration file                          | *component-name*.cmake |
| libraries       | component libraries, linked to esmx               | *component-name*       |
| fort\_module    | fortran module filename for NUOPC SetServices     | *component-name*.mod   |
| install\_prefix | root directory for installation                   | install                |
| config\_dir     | subdirectory for cmake configuration file         | cmake                  |
| library\_dir    | subdirectory for library file                     | lib                    |
| include\_dir    | subdirectory for fortran module file              | include                |
| link\_libraries | external libraries, linked to esmx                | *None*                 |
| link\_paths     | search path or environment var for link libraries | *None*                 |
| git\_repository | URL for downloading git repository                | *None*                 |
| git\_tag        | tag for downloading git repository                | *None*                 |
| git\_dir        | download directory for git repository             | *None*                 |

### CODE REVIEW

**Comment by uturuncoglu** [comment]
@danrosen25 it seems that the components in the photo code still uses Makefiles to create cmake files. What do I need to do in component side to make it compatible with ESMX build. Could you also point me a documentation or instructions. I am plaining to test it with my application to see what happens.

**Comment by danrosen25** [comment]
@theurich @uturuncoglu 
I've made progress with the changes to ESMX builds that I'd like you to review.

- I've added a list of [build options](https://github.com/esmf-org/esmf/tree/feature/esmx_cmake/src/addon/ESMX#esmxbuildyaml) to esmxBuild.yaml, most notably the build_type option. This option allows you to call the ESMX CMake build system and build a component as an ExternalProject, a subdirectory, or a previous installation.
- I have an example here: [https://github.com/esmf-org/nuopc-app-prototypes/tree/feature/esmx_cmake/ESMX_SingleModelProto](https://github.com/esmf-org/nuopc-app-prototypes/tree/feature/esmx_cmake/ESMX_SingleModelProto)
- I made sure that the changes are backwards compatible with [https://github.com/esmf-org/nuopc-app-prototypes/tree/feature/esmx_cmake/ESMX_AtmOcnProto](https://github.com/esmf-org/nuopc-app-prototypes/tree/feature/esmx_cmake/ESMX_AtmOcnProto)
- Users can specify the build configuration file (esmxBuild.yaml) by passing -DESMX_BUILD_FILE to the ESMX CMake build system
- I'd like to add something similar to this [build script](https://github.com/esmf-org/nuopc-app-prototypes/blob/feature/esmx_cmake/ESMX_SingleModelProto/build.sh) to the ESMF bin directory. This would eliminate the need for users to write any code related to the application or driver build system. They would only need a ESMX_BUILD_FILE.
- When you're reviewing please keep in mind that I'd like you to help me decide on the configuration options and how they are defaulted as these will be user facing.

**Comment by danrosen25** [comment]
> @danrosen25 it seems that the components in the photo code still uses Makefiles to create cmake files. What do I need to do in component side to make it compatible with ESMX build. Could you also point me a documentation or instructions. I am plaining to test it with my application to see what happens.

@uturuncoglu Take a look at my previous comment and also this [example](https://github.com/esmf-org/nuopc-app-prototypes/tree/feature/esmx_cmake/ESMX_SingleModelProto). I haven't made changes to the other ESMX_ examples. I also haven't added an option for build_type: make but I plan to do so. It's just a little more difficult because the dependency information can be located anywhere in the make system.

**Comment by theurich** [comment]
@danrosen25 - The `develop` branch for `esmf` and  `nuopc-app-prototypes` repos are ready now for you to use in your ESMX work. All of the updates wrt HConfig/YAML usage are completed.

You will see, in the ESMX context, there was a renaming of `esmx.F90` -> `ESMX_App.F90` (as per our previous conversation). I also used the chance to clean up the code under for both the App and Driver level. You will probably see conflicts when you try to merge this into your branch, but I think it'll be straight forward to figure out how to deal with it. Let me know if you run into any issues or have questions.

The final format of the `esmxRun.yaml`, e.g. for the `ESMX_AtmOcnProto` prototype looks pretty much the way we last discussed it:
```
ESMX:

  App:
    globalResourceControl:  true
    logKindFlag:            ESMF_LOGKIND_Multi
    logAppendFlag:          false
    logFlush:               true
#    fieldDictionary:        ./fd.yaml    # not currently used by this example
    startTime:              2012-10-24T18:00:00
    stopTime:               2012-10-24T19:00:00

  Driver:
    componentList:          [ATM, OCN]
    attributes:
      Verbosity: low

    runSequence: |
      @900
        ATM -> OCN
        OCN -> ATM
        ATM
        OCN
      @


ATM:
  model:            Tawas     # model value is case insensitive to match Fortran
  ompNumThreads:    4
  attributes:
    Verbosity:  low
  petList:          [3, [2-0]]  # petList is list of scalars and lists.
                                # each list again can be of scalars and lists
                                # recursively.

OCN:
  model:            lumo
  petList:          [0-1, 3]
  attributes:
    Verbosity:  low
```

For the transition of `ESMX_Data.F90` to HConfig/YAML, the relevant section in the reference manual is https://earthsystemmodeling.org/docs/nightly/develop/ESMF_refdoc/node6.html#SECTION060100000000000000000.

**Comment by theurich** [comment]
@danrosen25 - how is this work progressing? There are some conflicts (as expected, nothing major). I think the best way forward might be to merge `develop` into `feature/esmx_cmake` and deal with the conflicts.

**Comment by danrosen25** [comment]
@theurich It would be helpful if the HConfig class gave more context on this error. See attached configuration file (renamed as .txt for GitHub upload).
```
ESMCI_HConfig.C:391 ESMCI::HConfig::loadFile() Internal error: Bad condition  - Caught exception loading content from file: esmxRun.yaml
ESMCI_HConfig_F.C:216 c_esmc_hconfigload() Internal error: Bad condition  - Internal subroutine call returned Error
ESMF_HConfig.F90:8204 ESMF_HConfigFileLoad() Internal error: Bad condition  - Internal subroutine call returned Error
ESMF_Config.F90:2888 ESMF_ConfigLoadFile Internal error: Bad condition  - Internal subroutine call returned 
[esmxRun.txt](https://github.com/esmf-org/esmf/files/11738136/esmxRun.txt)
Error
ESMF_Init.F90:682 ESMF_FrameworkInternalInit Internal error: Bad condition  - Internal subroutine call returned Error
src/addon/ESMX/ESMF_App.F90:36 Operation not yet supported  - Passing error in return code
```
[esmxRun.txt](https://github.com/esmf-org/esmf/files/11738139/esmxRun.txt)

**Comment by danrosen25** [comment]
I fixed up the ESMX Data component to use HConfig and I merged esmx_cmake into this branch. Do you want to take a look at this?

Here's how ESMX Data component is configured after HConfig
https://github.com/esmf-org/esmf/blob/feature/esmx_cmake/src/addon/ESMX/Tests/esmx-data/esmxRun.yaml

I think the last change should be to check that esmxRun.yaml exists in the ESMX Driver component. Also to make the filename flexible. How much time do we have to get this done?

**Comment by danrosen25** [comment]
@theurich This sounds good. Should we delete feature/esmx_cmake_yaml now that it's merged into feature/esmx_cmake?

**Comment by theurich** [comment]
Yes, I just went ahead and deleted feature/esmx_cmake_yaml. I'll branch off from feature/esmx_cmake for anything else.

**Comment by theurich** [comment]
@danrosen25 - The changes are on the branch. ESMX_App now looks at command line argument 1, and if it is present, it is used as the config filename. If not, defaults to `esmxRun.yaml`.

**Comment by theurich** [comment]
The two items still needed (as identified in conversation under PR #152) before this PR is ready are:
- Remove `x_comp_hconfig_check` from `ESMX_Data` and replace with `ESMF_HConfigValidateMapKeys`.
- Remove the paragraph in `README.md` about "detached head" of components.

**Comment by theurich** [comment]
> The two items still needed (as identified in conversation under PR #152) before this PR is ready are:
> 
> * Remove `x_comp_hconfig_check` from `ESMX_Data` and replace with `ESMF_HConfigValidateMapKeys`.
> * Remove the paragraph in `README.md` about "detached head" of components.

@danrosen25 let me know if you're working on these, or if you want me to make those two changes. Once they are in, I think the PR is ready to go into `develop`, and we can wrap up 8.5.0 development.

**Comment by danrosen25** [comment]
I'm working on them and I'll have them done today.

**Comment by danrosen25** [comment]
Done.

**Review by theurich — APPROVED** [review]
I have reviewed the changes, and tested the branch locally, also against nuopc-app-prototypes branch feature/esmx_cmake. The code in this PR works as expected.

**Comment by theurich** [comment]
@danrosen25, unless @uturuncoglu has objections, please go ahead and merge this PR into develop. I have a few unrelated changes coming into develop after this, and then we should have a snapshot that @uturuncoglu can test.

**Comment by uturuncoglu** [comment]
@theurich It is hard to say anything before testing. I think once we have snapshot, I could start to test it and I could have more concrete information about the new implementation.

**Comment by theurich** [comment]
Yes, that is what I thought @uturuncoglu. @danrosen25 please go ahead and merge the PR. Thanks!

**Comment by danrosen25** [comment]
@theurich @uturuncoglu
This is going to be a large merge (26 files and 4k lines) with several intermediary merges. Do you want me to merge or merge squash? I've outlined the commit log notes below.

```
Improved ESMX Layer - ESMF 8.5.0

* Set ESMX build file using ESMX_BUILD_FILE
* Add application, component, and test configuration options to ESMX_BUILD_FILE
* Add feature to build components using ESMX
* Add feature to search for component cmake config, libraries, and modules
* Add testing feature using CTest
* Fix library link, previously in component cmake config
* Fix existing ESMF target in FindESMF.cmake
* Update ESMX to use HConfig for run configuration
* Command line filename for ESMF App configuration
* Add feature to fetch git repositories
* Add ESMX Data component
* Add HConfig subroutine to check map keys ESMF_HConfigValidateMapKeys
* Add ESMX_Builder script to ESMF installation
* Update ESMX documentation
* Cleanup output for FieldRegridStore
* Add ESMF initialization option for reading config filename from arguments

Co-authored-by: Gerhard Theurich <gerhard.j.theurich@noaa.gov>
```

**Comment by theurich** [comment]
@danrosen25 - a squash merge seems appropriate to me.

**Pull request merged**
