### PR TITLE
Update copyright

### PR DESCRIPTION
**Pull request by billsacks**
I'm opening this for informational purposes – no need to review.

The replacements were straightforward:
1. Replaced "Copyright 2002-2022" with "Copyright (c) 2002-2022"
2. Replaced "Copyright (c) 2002-2022" with "Copyright (c) 2002-2023"

I did a quick look through the list of files changed. Finally, I checked for files with "Copyright" but not "Copyright (c) 2002-2023". I found one file that needed to be fixed (there was a line break introduced in the copyright notice; I fixed this). Other than that, instances of copyright were just in:
- Third-party things with different copyright notices
- eps files

### CODE REVIEW

**Comment by billsacks** [comment]
Oops, I posted the original comment prematurely. I have edited it to include everything I wanted to, but for the sake of people who just are looking at their notifications and don't see the updated version, I am copying it here:

The replacements were straightforward:
1. Replaced "Copyright 2002-2022" with "Copyright (c) 2002-2022"
2. Replaced "Copyright (c) 2002-2022" with "Copyright (c) 2002-2023"

I did a quick look through the list of files changed. Finally, I checked for files with "Copyright" but not "Copyright (c) 2002-2023". I found one file that needed to be fixed (there was a line break introduced in the copyright notice; I fixed this). Other than that, instances of copyright were just in:
- Third-party things with different copyright notices
- eps files

**Comment by theurich** [comment]
@billsacks - one file I still seeing that contains a  `-2022` copyright date is `src/addon/esmpy/doc/conf.py`.  It's certainly a different format, but probably needs to be updated, too.

**Comment by billsacks** [comment]
@theurich - good catch, thanks! I'll fix that.

**Comment by theurich** [comment]
Nice to have the copyright update dealt with. Thanks!
How easy do you think it is to bring the update into patch/8.4.1?

**Comment by billsacks** [comment]
> How easy do you think it is to bring the update into patch/8.4.1?

Easy and done now.

**Comment by billsacks** [comment]
The updating of copyright just took me a few minutes per branch. The harder piece was trying to confirm that I didn't miss anything that was in a non-standard format. I caught one thing (which I have fixed to be in a standard format) and you caught another (which will probably never be in the standard format, but I'll document that when I put together a wiki page on this process).

**Comment by theurich** [comment]
Did you cherry-pick into patch/8.4.1? I could not tell you right now if there are any files added/deleted on develop since v8.4.0, so that was sort the nagging question in my mind with this. Just curious.

**Comment by billsacks** [comment]
No, I redid the search & replace.

**Comment by theurich** [comment]
Okay, great. That's what makes most sense to me, too, for this situation. Thanks for getting this done quickly!

**Comment by billsacks** [comment]
And I just did similar updates for nuopc-app-prototypes and esmf-extended-tests (the latter had a mix of copyright dates of 2020, 2021 and 2022; I think I got them all).

Tomorrow I'll write up a wiki page describing the process along with some git grep commands that are useful to confirm that you have caught everything. (TIL: git grep supports boolean operators, as in `git grep -i -l -e 'copyright.*20' --and --not -e 'Copyright (c) 2002-2023'`. Very useful!)

**Comment by theurich** [comment]
Fantastic! Yes, having that writeup for the wiki will be very useful in the future. I think we've done this differently every year, and by different folks on the team (all moved on by now). So finally having a standard way documented of handling this is more than overdue. Thanks again for taking this on and getting it done, especially with 8.4.1 on the way out.

**Pull request merged**
