### PR TITLE
Ensure full test coverage of public API before release 8.5.0

### PR DESCRIPTION
**Pull request by theurich**
Add unit tests for APIs flagged by the test-coverage action. Also take care of some minor doc issues and format alignment.

### CODE REVIEW

**Comment by theurich** [comment]
@danrosen25 @billsacks @uturuncoglu - Since develop is frozen, we need a review for this to go in. I requested review on the PR from all core team members currently around (Bob being out). This isn't a big PR, just need a quick okay from everyone before squash merging it into develop for the night. I tested it locally, and all looking clean. Thanks.

**Review by uturuncoglu — APPROVED** [review]

**Comment by uturuncoglu** [comment]
@theurich Thanks for fixing issues. It looks good to me.

**Review by billsacks — APPROVED** [review]
Looks good to me - thanks!

**Comment by theurich** [comment]
@danrosen25 Just need your approval to bring this into develop as well.

**Review by danrosen25 — APPROVED** [review]
The added tests look good. If `all_tests` has passed on your testing machine then we're good.

**Pull request merged**
